# Generated by Django 3.2.4 on 2021-06-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210629_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cheque_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='cheque_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='type_payment',
            field=models.CharField(choices=[('cash', 'cash'), ('netbanking', 'netbanking'), ('upi', 'upi'), ('cheque', 'cheque')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='GSTno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
