# Generated by Django 3.2.4 on 2021-06-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210629_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cheque_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cheque_no',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='type_payment',
        ),
    ]
