# Generated by Django 3.2.5 on 2021-07-03 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
        ('subcategory', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serno', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('qun', models.CharField(max_length=100)),
                ('companyname', models.CharField(max_length=100)),
                ('maincategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='category.category')),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='material.material')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='subcategory.subcategory')),
            ],
        ),
    ]
