# Generated by Django 3.2.5 on 2021-07-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qun',
            field=models.IntegerField(default=0),
        ),
    ]
