# Generated by Django 3.2.5 on 2021-07-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210719_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo1',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo2',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo3',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo4',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo5',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='product'),
        ),
    ]
