# Generated by Django 3.2.5 on 2021-07-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210719_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo1',
            field=models.ImageField(default='default.jpg', upload_to='product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo2',
            field=models.ImageField(default='default.jpg', upload_to='product'),
        ),
    ]
