# Generated by Django 3.2.4 on 2021-06-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=80)),
                ('bankname', models.CharField(max_length=80)),
                ('branchname', models.CharField(max_length=80)),
                ('acc', models.CharField(max_length=15)),
                ('ifsc', models.CharField(max_length=10)),
                ('phono', models.CharField(max_length=10)),
                ('upi', models.CharField(max_length=20)),
                ('balance', models.CharField(max_length=10)),
            ],
        ),
    ]
