# Generated by Django 3.2.4 on 2021-06-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerPayment', '0003_auto_20210629_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerpayment',
            name='cash',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
