# Generated by Django 3.2.4 on 2021-06-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerPayment', '0004_ownerpayment_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerpayment',
            name='cash',
            field=models.IntegerField(default=0),
        ),
    ]
