# Generated by Django 3.2.5 on 2021-07-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='documnets',
            field=models.FileField(default='', upload_to='docs'),
        ),
        migrations.AddField(
            model_name='emp',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='emp',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
