# Generated by Django 3.2.5 on 2021-07-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210704_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
