# Generated by Django 3.2.5 on 2021-07-03 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prodoutward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qun', models.CharField(max_length=100)),
                ('rates', models.FloatField(max_length=100)),
                ('prices', models.FloatField(max_length=100)),
                ('discounts', models.FloatField(blank=True, max_length=100, null=True)),
                ('GSTno', models.CharField(blank=True, max_length=100, null=True)),
                ('productname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product')),
            ],
        ),
    ]
