# Generated by Django 3.2.5 on 2021-07-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productout', '0002_prodoutward_is_billed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodoutward',
            name='GSTno',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prodoutward',
            name='discounts',
            field=models.FloatField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
