# Generated by Django 3.2.5 on 2021-07-11 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inward_purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inward_purchase',
            name='sup',
        ),
    ]
