# Generated by Django 3.2.5 on 2021-07-11 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('inward_purchase', '0002_remove_inward_purchase_sup'),
    ]

    operations = [
        migrations.AddField(
            model_name='inward_purchase',
            name='spp',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='supplier.supplier'),
        ),
    ]
