# Generated by Django 3.2.5 on 2021-07-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inward_purchase', '0003_inward_purchase_spp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward_purchase',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='inward_purchase',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
