# Generated by Django 3.2.5 on 2021-07-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inward_purchase', '0004_auto_20210713_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward_purchase',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
