# Generated by Django 3.2.5 on 2021-07-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inward_purchase', '0005_alter_inward_purchase_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward_purchase',
            name='total',
            field=models.IntegerField(),
        ),
    ]
