# Generated by Django 3.2.5 on 2021-07-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inward_purchase', '0006_alter_inward_purchase_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='inward_purchase',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
