# Generated by Django 3.2.5 on 2021-07-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodcutin',
            name='is_billed',
            field=models.BooleanField(default=False),
        ),
    ]
