# Generated by Django 3.2.5 on 2021-07-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productin', '0003_auto_20210713_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcutin',
            name='qun',
            field=models.IntegerField(),
        ),
    ]
