# Generated by Django 3.2.5 on 2021-07-11 11:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outward_purchase', '0001_initial'),
        ('customerpayment', '0002_auto_20210701_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpay',
            name='bill',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='outward_purchase.outward_purchase'),
        ),
        migrations.AddField(
            model_name='customerpay',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 11, 15, 56, 103170)),
        ),
    ]
