# Generated by Django 3.2.5 on 2021-07-16 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerpayment', '0009_auto_20210716_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpay',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 14, 41, 16, 177537)),
        ),
    ]
