# Generated by Django 3.2.5 on 2021-07-17 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerpayment', '0013_alter_customerpay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpay',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 17, 9, 2, 55, 833108)),
        ),
    ]
