# Generated by Django 3.2.5 on 2021-07-19 16:49

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerpayment', '0018_alter_customerpay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpay',
            name='cash',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='customerpay',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 19, 16, 49, 3, 576087)),
        ),
    ]
