# Generated by Django 3.2.5 on 2021-07-11 10:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inward_purchase', '0003_inward_purchase_spp'),
        ('Supplierpayment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppayment',
            name='bill',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='inward_purchase.inward_purchase'),
        ),
        migrations.AddField(
            model_name='suppayment',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 10, 56, 35, 460848)),
        ),
    ]
