# Generated by Django 3.2.5 on 2021-07-16 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplierpayment', '0006_alter_suppayment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppayment',
            name='sup',
        ),
        migrations.AlterField(
            model_name='suppayment',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 31, 29, 103536)),
        ),
    ]
