# Generated by Django 3.2.5 on 2021-07-16 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplierpayment', '0007_auto_20210716_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppayment',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 37, 33, 118254)),
        ),
    ]
